### ISSUE TITLE
Create Wireframe using https://balsamiq.com/

### ISSUE THREAD

**Issue by lalov1** [chingu-voyage3/geckos-32#1]

**Comment by JohnDuhan** [comment]
Github doesn't support the balsamiq file type here. If you would like to view the wireframe via the balsamiq cloud or desktop app, I'll need your email address to share the presentation.

[Music Library Catalogue.pdf](https://github.com/chingu-voyage3/geckos-32/files/1583282/Music.Library.Catalogue.pdf)
